# Generated by Django 2.2.4 on 2019-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20190815_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
