# Generated by Django 2.2.4 on 2019-08-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user',
            new_name='project',
        ),
    ]
